[package]
name = "convert-nonogram"
description = "A converter from images to nonogram clues"
version = "0.1.2"
authors = ["Paul Stansifer <paul.stansifer@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["nonogram"]
readme = "README.md"
repository = "https://github.com/paulstansifer/convert-nonogram"

[dependencies]
image = "0.23.11"
quick-xml = "0.37.1"
indoc = "1.0"
ndarray = "0.16.1"
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
