[package]
name = "convert-nonogram"
version = "0.1.0"
authors = ["Paul Stansifer <paul.stansifer@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["nonogram"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.11"
clap = "2.33.3"
quick-xml = "0.20.0"
indoc = "1.0"