[package]
name = "convert-nonogram"
description = "A converter from images to nonogram clues"
version = "0.1.1"
authors = ["Paul Stansifer <paul.stansifer@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["nonogram"]
readme = "README.md"
repository = "https://github.com/paulstansifer/convert-nonogram"

[dependencies]
image = "0.23.11"
clap = "2.33.3"
quick-xml = "0.20.0"
indoc = "1.0"